// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.ConcurrentDictionaries(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.DivZero(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.DumpGen(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.GCPOHTests(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.GCTests(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.LineNums(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.LLDBPluginTests(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.NestedExceptionTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.OtherCommands(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.Overflow(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.Reflection(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.SimpleThrow(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.StackTests(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:SOS.TaskNestedException(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
