// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventCounterPipelineUnitTests.TestCounterEventPipeline(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventCounterTriggerTests.EventCounterTriggerWithEventPipePipelineTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsAllCategoriesAllLevels(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsAllCategoriesDefaultLevel(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsAllCategoriesDefaultLevelFallback(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsAllCategoriesDefaultLevelNoneNotSupported(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsUseAppFilters(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsUseAppFiltersAndFilterSpecs(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventLogsPipelineUnitTests.TestLogsWildcardCategory(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventTracePipelineUnitTests.TestEventStreamCleanup(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.EventTracePipelineUnitTests.TestTraceStopAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
