// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.BasicEventPipeSessionTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.BasicEventPipeSessionTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.EventPipeSessionStreamTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.EventPipeSessionStreamTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.EventPipeSessionUnavailableTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.EventPipeSessionUnavailableTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.StartEventPipeSessionWithSingleProviderTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.EventPipeSessionTests.StartEventPipeSessionWithSingleProviderTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetProcessInfoTests.BasicProcessInfoNoSuspendTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetProcessInfoTests.BasicProcessInfoNoSuspendTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetProcessInfoTests.BasicProcessInfoSuspendTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetProcessInfoTests.BasicProcessInfoSuspendTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetPublishedProcessesTest.MultiplePublishedProcessTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetPublishedProcessesTest.PublishedProcessTest1(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.GetPublishedProcessesTest.WaitForConnectionTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ProcessEnvironmentTests.BasicEnvTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ProcessEnvironmentTests.BasicEnvTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerNoCreateTransportAfterDispose(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerNonExistingRuntimeIdentifierTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerNonExistingRuntimeIdentifierTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerSingleTargetExitsClientInviableTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerSingleTargetExitsClientInviableTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerSingleTargetMultipleUseClientTest(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.NETCore.Client.ReversedServerTests.ReversedServerSingleTargetMultipleUseClientTestAsync(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
