// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.Attach1(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.Attach2(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.Attach3(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.CreateDebuggingInterfaceFromVersion(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.CreateDebuggingInterfaceFromVersion2(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.CreateDebuggingInterfaceFromVersion3(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.CreateDebuggingInterfaceFromVersionEx(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.EnumerateCLRs(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.Launch1(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.Launch2(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "CA1825:Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.DbgShimTests.Launch3(Microsoft.Diagnostics.TestHelpers.TestConfiguration)~System.Threading.Tasks.Task")]
